-- database/users.sql
--
-- Dashboard user accounts — separate from ML tenant JWTs.
--
-- Design
-- ------
-- * users are dashboard logins (email + bcrypt password hash)
-- * Each user is assigned a role: "admin" (sees everything) or "viewer" (own tenant only)
-- * tenant_id is NULL for admin users (they see all tenants)
-- * password_hash uses pgcrypto crypt() / bcrypt — bcrypt is handled in Python (bcrypt lib)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";   -- case-insensitive email comparison

CREATE TABLE IF NOT EXISTS dashboard_users (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email           CITEXT      NOT NULL UNIQUE,
    password_hash   TEXT        NOT NULL,    -- bcrypt hash managed by Python
    display_name    TEXT        NOT NULL DEFAULT '',
    role            TEXT        NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'viewer')),
    tenant_id       TEXT,                    -- NULL = admin sees all tenants
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_dashboard_users_email ON dashboard_users (email);
CREATE INDEX IF NOT EXISTS idx_dashboard_users_tenant ON dashboard_users (tenant_id) WHERE tenant_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Default admin seed (password: "admin123" — CHANGE IN PRODUCTION)
-- The hash is generated by: bcrypt.hashpw(b"admin123", bcrypt.gensalt()).decode()
-- This INSERT is intentionally idempotent via ON CONFLICT DO NOTHING.
-- ---------------------------------------------------------------------------
-- INSERT INTO dashboard_users (email, password_hash, display_name, role, tenant_id)
-- VALUES (
--     'admin@example.com',
--     '$2b$12$PLACEHOLDER_CHANGE_ME',
--     'Admin',
--     'admin',
--     NULL
-- ) ON CONFLICT (email) DO NOTHING;
